### ISSUE TITLE
Stability of dependencies.

### ISSUE THREAD

**Issue by SamMousa** [johnitvn/yii2-settings#1]
Your dependencies all have \* as required version.
It is not correct to mark your package as stable (1.0.4) when it depends on unstable packages. 

Also this causes installation issues with respect to minium stability settings.

**Comment by johnitvn** [comment]
I updated project!

Other Links
[Free download premium wordpress theme](http://w3deep.com/wordpress-theme/)
[Free download premium html template](http://w3deep.com/html-template/)
